link-sdk:
	(rm -f ./source/AdobeEdge.brs)
	(rm -f ./components/adobe)
	(ln -s ../../../code/components/adobe ./components/adobe)
	(ln -s ../../../code/AdobeEdge.brs ./source/AdobeEdge.brs)

# bsc: https://github.com/rokucommunity/brighterscript
install-bsc:
	(npm install brighterscript -g)

build:
	(bsc)